/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDiaAggregator,
  IDiaAggregatorInterface,
} from "../IDiaAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "key",
        type: "string",
      },
    ],
    name: "getValue",
    outputs: [
      {
        internalType: "uint128",
        name: "price",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "timestamp",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IDiaAggregator__factory {
  static readonly abi = _abi;
  static createInterface(): IDiaAggregatorInterface {
    return new utils.Interface(_abi) as IDiaAggregatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDiaAggregator {
    return new Contract(address, _abi, signerOrProvider) as IDiaAggregator;
  }
}
