/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { PoolInfo, PoolInfoInterface } from "../PoolInfo";

const _abi = [
  {
    inputs: [
      {
        name: "_provider",
        type: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
    name: "constructor",
  },
  {
    inputs: [
      {
        name: "_pool",
        type: "address",
      },
    ],
    name: "get_pool_coins",
    outputs: [
      {
        name: "coins",
        type: "address[8]",
      },
      {
        name: "underlying_coins",
        type: "address[8]",
      },
      {
        name: "decimals",
        type: "uint256[8]",
      },
      {
        name: "underlying_decimals",
        type: "uint256[8]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        name: "_pool",
        type: "address",
      },
    ],
    name: "get_pool_info",
    outputs: [
      {
        name: "balances",
        type: "uint256[8]",
      },
      {
        name: "underlying_balances",
        type: "uint256[8]",
      },
      {
        name: "decimals",
        type: "uint256[8]",
      },
      {
        name: "underlying_decimals",
        type: "uint256[8]",
      },
      {
        name: "rates",
        type: "uint256[8]",
      },
      {
        name: "lp_token",
        type: "address",
      },
      {
        name: "lp_token_total_supply",
        type: "uint256",
      },
      {
        name: "lp_token_virtual_price",
        type: "uint256",
      },
      {
        name: "lp_token_symbol",
        type: "string",
      },
      {
        components: [
          {
            name: "A",
            type: "uint256",
          },
          {
            name: "future_A",
            type: "uint256",
          },
          {
            name: "fee",
            type: "uint256",
          },
          {
            name: "admin_fee",
            type: "uint256",
          },
          {
            name: "future_fee",
            type: "uint256",
          },
          {
            name: "future_admin_fee",
            type: "uint256",
          },
          {
            name: "future_owner",
            type: "address",
          },
          {
            name: "initial_A",
            type: "uint256",
          },
          {
            name: "initial_A_time",
            type: "uint256",
          },
          {
            name: "future_A_time",
            type: "uint256",
          },
        ],
        name: "params",
        type: "tuple",
      },
      {
        name: "is_meta",
        type: "bool",
      },
      {
        name: "name",
        type: "string",
      },
      {
        name: "asset_type",
        type: "uint256",
      },
      {
        name: "base_pool",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "address_provider",
    outputs: [
      {
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PoolInfo__factory {
  static readonly abi = _abi;
  static createInterface(): PoolInfoInterface {
    return new utils.Interface(_abi) as PoolInfoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoolInfo {
    return new Contract(address, _abi, signerOrProvider) as PoolInfo;
  }
}
